name: mywords
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

  # To see newer versions, run: `flutter pub outdated`
  # To upgrade dependencies to the latest versions, run: `flutter pub upgrade --major-versions`

dependencies:
  flutter:
    sdk: flutter

  # visuals
  cupertino_icons: ^1.0.6
  flutter_svg:

  # core
  get_it: ^8.0.3
  shared_preferences: ^2.3.0
  flutter_bloc: ^9.1.0
  dio: ^5.8.0+1
  dartz: ^0.10.1
  pinput: ^5.0.1
  url_launcher: ^6.2.2
  webview_flutter: ^4.0.0



  file_picker: ^8.3.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  flutter_pdfview: ^1.3.0
  syncfusion_flutter_pdf: ^22.1.34
  device_info_plus: ^9.0.2
  docx_to_text: ^1.0.1







  logger: ^2.0.2+1


dev_dependencies:

  # dev dependencies
  flutter_test:
    sdk: flutter

#  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/
