name: mywords
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

  # To see newer versions, run: `flutter pub outdated`
  # To upgrade dependencies to the latest versions, run: `flutter pub upgrade --major-versions`


dependencies:
  flutter:
    sdk: flutter

  # Authentication & User Management
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # State Management & Architecture
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  dartz: ^0.10.1

  # Firebase Services
  firebase_core: 3.13.0
  firebase_analytics: 11.3.6

  # Storage & Preferences
  shared_preferences: ^2.5.3

  # Network & API
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  webview_flutter: ^4.11.0

  # Document Processing
  syncfusion_flutter_pdf: ^29.1.39
  docx_to_text: ^1.0.1
  file_picker: ^10.1.2

  # UI/UX & Visualization
  flutter_svg: ^2.1.0
  flutter_screenutil: ^5.9.3
  pinput: ^5.0.1
  flutter_animate: ^4.5.2

  # Device & Permissions
  permission_handler: ^12.0.0+1
  device_info_plus: ^11.4.0

  # Monetization
  purchases_flutter: ^8.7.5

  # Utilities & Debugging
  logger: ^2.0.2+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
#  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/


flutter_launcher_icons:
  android: false
  ios: 'AppIcon'
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

  # Add this to your pubspec.yaml
  dependency_overrides:
    firebase_analytics: 11.3.6
    firebase_analytics_platform_interface: 4.3.4
    firebase_analytics_web: 0.5.10+9