// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjWvqlw3QQMAO36tzWuiDN52lrkC-ti_8',
    appId: '1:951118939478:android:e40db9e292898acda6c2f7',
    messagingSenderId: '951118939478',
    projectId: 'mywordsai',
    storageBucket: 'mywordsai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU5HbOiR6VRzcq083erJORQiGuQe87vuM',
    appId: '1:951118939478:ios:35ce8b26fb0dd11aa6c2f7',
    messagingSenderId: '951118939478',
    projectId: 'mywordsai',
    storageBucket: 'mywordsai.firebasestorage.app',
    androidClientId: '951118939478-2uohcn5agq2abu7bcjud0ut9d1ruk454.apps.googleusercontent.com',
    iosClientId: '951118939478-eueqfv6l1s9kdg33al8qunr6b7hu1r8b.apps.googleusercontent.com',
    iosBundleId: 'com.ai.mywords',
  );
}
